from .content import *
from .course_syllabus import *
from .details import *
from .file import *
from .grade_determination import *
from .list_block import *
from .multiple_choice_question import *
from .schedule import *
from .table import *
from .true_false_question import *
from .video import *
